
server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    server-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: hello-world
            preLogger: false
            postLogger: true
      routes:
        - id: discovery-client1
          uri: lb://DISCOVERY-CLIENT1
          predicates:
            - Path= /client1/**
          filters:
            - CustomFilter

        - id: discovery-client2
          uri: lb://DISCOVERY-CLIENT2
          predicates:
            - Path= /client2/**
          filters:
            - CustomFilter

        - id: discovery client03
          uri: http://192.168.0.40:9002/
          predicates:
            - Path= /client03/**
          filters:
            - CustomFilter
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path= /user/**
          filters:
            - CustomFilter

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace